name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Syntax check
        run: |
          python -m py_compile user_data/strategies/NewsHeliusBitqueryML.py
      - name: Import check (без запуска Freqtrade)
        run: |
          python -c "import sys; sys.path.append('user_data/strategies'); import NewsHeliusBitqueryML; print('Strategy import OK')"
